# ═══════════════════════════════════════════════════════════════════════════════
# markdownlint Configuration
# ═══════════════════════════════════════════════════════════════════════════════
#
# 📝 Node.js style checker and lint tool for Markdown/CommonMark files
#    that enforces standards and consistency across documentation.
#
# 📚 Resources:
#    • Documentation: https://github.com/DavidAnson/markdownlint
#    • Rules:         https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
#    • Configuration: https://github.com/DavidAnson/markdownlint#configuration
#
# ═══════════════════════════════════════════════════════════════════════════════

default: true